// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC1orF0OjBOAIisYxBb5eHFAzIQ9m1t9s',
    appId: '1:255665597270:web:75d40f5128be82b734c4f7',
    messagingSenderId: '255665597270',
    projectId: 'trello-app-756e6',
    authDomain: 'trello-app-756e6.firebaseapp.com',
    storageBucket: 'trello-app-756e6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWSnQgAlfg30Kzf4ZJXtcwBqWRMooNW1M',
    appId: '1:255665597270:android:b3f53baf029511ff34c4f7',
    messagingSenderId: '255665597270',
    projectId: 'trello-app-756e6',
    storageBucket: 'trello-app-756e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMhaDHcb_Wnftrt7RwFjghyMNBz4pq-Qc',
    appId: '1:255665597270:ios:281bd39392318e8e34c4f7',
    messagingSenderId: '255665597270',
    projectId: 'trello-app-756e6',
    storageBucket: 'trello-app-756e6.appspot.com',
    iosClientId: '255665597270-oqasrd46ai75rbqhrtp0cks8nr94igbt.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMhaDHcb_Wnftrt7RwFjghyMNBz4pq-Qc',
    appId: '1:255665597270:ios:281bd39392318e8e34c4f7',
    messagingSenderId: '255665597270',
    projectId: 'trello-app-756e6',
    storageBucket: 'trello-app-756e6.appspot.com',
    iosClientId: '255665597270-oqasrd46ai75rbqhrtp0cks8nr94igbt.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDC1orF0OjBOAIisYxBb5eHFAzIQ9m1t9s',
    appId: '1:255665597270:web:7f9601920d47fbd034c4f7',
    messagingSenderId: '255665597270',
    projectId: 'trello-app-756e6',
    authDomain: 'trello-app-756e6.firebaseapp.com',
    storageBucket: 'trello-app-756e6.appspot.com',
  );
}
